spring:
  application:
    name: tarefas
  datasource:
    url: jdbc:mysql://localhost:3306/tarefas?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true
